- hosts: localhost
  vars:
    OSP_GUID: "{{ lookup('env','OSP_GUID') }}"
    OSP_DOMAIN: "{{ lookup('env','OSP_DOMAIN') }}"
    OPENTLC_ID: "{{ lookup('env','OPENTLC_ID') }}"
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.blue.osp.opentlc.com"
       group: workstation
       ansible_user: cloud-user
       ansible_ssh_private_key_file: /root/.ssh/openstack.pem

- hosts: workstation
  become: yes
  roles:
    - osp-instance-delete
